blank_issues_enabled: false
contact_links:
  - name: Questions, Discussions, Ideas
    url: https://github.com/RomanSoloweow/Rider-Visual-Studio-2019-Dark-Theme/discussions/new
    about: Please ask and answer questions here.
